/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ForgetPasswordRouteImport } from './routes/forgetPassword'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as HomeNodeWithExpressPostgresRouteImport } from './routes/home/node-with-express-postgres'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgetPasswordRoute = ForgetPasswordRouteImport.update({
  id: '/forgetPassword',
  path: '/forgetPassword',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRoute,
} as any)
const HomeNodeWithExpressPostgresRoute =
  HomeNodeWithExpressPostgresRouteImport.update({
    id: '/node-with-express-postgres',
    path: '/node-with-express-postgres',
    getParentRoute: () => HomeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgetPassword': typeof ForgetPasswordRoute
  '/home': typeof HomeRouteWithChildren
  '/register': typeof RegisterRoute
  '/home/node-with-express-postgres': typeof HomeNodeWithExpressPostgresRoute
  '/home/': typeof HomeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgetPassword': typeof ForgetPasswordRoute
  '/register': typeof RegisterRoute
  '/home/node-with-express-postgres': typeof HomeNodeWithExpressPostgresRoute
  '/home': typeof HomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgetPassword': typeof ForgetPasswordRoute
  '/home': typeof HomeRouteWithChildren
  '/register': typeof RegisterRoute
  '/home/node-with-express-postgres': typeof HomeNodeWithExpressPostgresRoute
  '/home/': typeof HomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgetPassword'
    | '/home'
    | '/register'
    | '/home/node-with-express-postgres'
    | '/home/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgetPassword'
    | '/register'
    | '/home/node-with-express-postgres'
    | '/home'
  id:
    | '__root__'
    | '/'
    | '/forgetPassword'
    | '/home'
    | '/register'
    | '/home/node-with-express-postgres'
    | '/home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgetPasswordRoute: typeof ForgetPasswordRoute
  HomeRoute: typeof HomeRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgetPassword': {
      id: '/forgetPassword'
      path: '/forgetPassword'
      fullPath: '/forgetPassword'
      preLoaderRoute: typeof ForgetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/node-with-express-postgres': {
      id: '/home/node-with-express-postgres'
      path: '/node-with-express-postgres'
      fullPath: '/home/node-with-express-postgres'
      preLoaderRoute: typeof HomeNodeWithExpressPostgresRouteImport
      parentRoute: typeof HomeRoute
    }
  }
}

interface HomeRouteChildren {
  HomeNodeWithExpressPostgresRoute: typeof HomeNodeWithExpressPostgresRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeNodeWithExpressPostgresRoute: HomeNodeWithExpressPostgresRoute,
  HomeIndexRoute: HomeIndexRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgetPasswordRoute: ForgetPasswordRoute,
  HomeRoute: HomeRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
